version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: rag-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/chroma_db:/app/chroma_db # Persistance de la base vectorielle
      - ./backend/data:/app/data # Persistance des documents uploadés
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: rag-frontend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000 # Communication interne Docker
    depends_on:
      - backend
    restart: always
