name: DevSecOps Deploy to Oracle VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Déploiement sécurisé via SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          host: ${{ secrets.HOST_IP }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: OPENAI_API_KEY
          command_timeout: 30m
          script: |
            cd ~/chatbot-RAG-projet

            # 1. Récupération du code
            git fetch --all
            git reset --hard origin/main

            # 2. Injection du secret dans le .env local à la VM
            echo "OPENAI_API_KEY=$OPENAI_API_KEY" > .env

            # 3. Nettoyage du cache Docker sur la VM pour libérer l'espace disque

            # Arrêter proprement l'ancienne version pour libérer les ports
            sudo docker compose down

            # Construire et lancer la nouvelle version
            sudo docker compose up -d --build
